api_version: apex/v1
kind: Model
metadata:
  id: flux-dev-control-canny
  model: flux
  name: Flux Dev Control Canny
  version: 1.0.0
  description: Flux control canny is a 12B parameter model for image control.
  tags:
    - flux
    - dev
    - control 
    - canny
  author: Apex AI
  license: Apache-2.0
  demo_path: https://cdn.prod.website-files.com/650c3b59079d92475f37b68f/673f828bcc8490e83dc7791c_673f8284e07dee522e1c92f5_Canny%2520image%2520example%2520transparent%2520-%2520Canny%2520(3).png

spec:
  engine: flux
  model_type: control
  engine_type: torch
  denoise_type: base
  components:
  - type: scheduler
    label: Scheduler
    default: FlowMatchEulerDiscreteScheduler
    scheduler_options:
    - name: FlowMatchEulerDiscreteScheduler
      label: FlowMatch Euler Discrete Scheduler
      description: The FlowMatch Euler Discrete Scheduler is a scheduler for the Flux Dev Control Canny model.
      base: diffusers.FlowMatchEulerDiscreteScheduler
      config_path: black-forest-labs/FLUX.1-Canny-dev/scheduler/scheduler_config.json
    - name: FlowMatchDiscreteScheduler
      label: FlowMatch Discrete Scheduler
      description: The FlowMatch Discrete Scheduler is a scheduler for the Flux Dev Control Canny model.
      base: src.scheduler.FlowMatchDiscreteScheduler
      config:
        shift: 5.0
        reverse: true
        solver: euler
    - name: EulerDiscreteScheduler
      label: Euler Discrete Scheduler
      description: The Euler Discrete Scheduler is a scheduler for the Flux Dev Control Canny model.
      base: diffusers.EulerDiscreteScheduler

  - type: vae
    label: Flux VAE
    base: auto
    model_path: 
      - path: black-forest-labs/FLUX.1-dev/vae
        variant: default
        precision: fp16
  
  - type: text_encoder
    name: text_encoder
    label: CLIP Text Encoder
    base: CLIPTextModel
    model_path: 
      - path: black-forest-labs/FLUX.1-dev/text_encoder
        variant: default
        precision: fp16
    tokenizer_class: CLIPTokenizer
    tokenizer_name: black-forest-labs/FLUX.1-dev
    tokenizer_kwargs:
      subfolder: tokenizer
    
  - type: text_encoder
    name: text_encoder_2
    label: T5 Text Encoder
    base: T5EncoderModel
    model_path: 
      - path: black-forest-labs/FLUX.1-dev/text_encoder_2
        variant: default
        precision: fp16
    tokenizer_class: T5Tokenizer
    tokenizer_name: black-forest-labs/FLUX.1-dev
    tokenizer_kwargs:
      subfolder: tokenizer_2

  - type: transformer
    label: Flux Canny Transformer
    base: flux.base
    model_path: 
      - path: black-forest-labs/FLUX.1-Canny-dev/transformer
        variant: default
        precision: fp16
        type: safetensors
        resource_requirements:
          min_vram_gb: 8
          recommended_vram_gb: 16
      - path: https://huggingface.co/SporkySporkness/FLUX.1-Canny-dev-GGUF/resolve/main/flux1-canny-dev-fp16-F16-GGUF.gguf
        variant: default
        precision: fp16
        type: gguf
        resource_requirements:
          min_vram_gb: 8
          recommended_vram_gb: 16
      - path: https://huggingface.co/SporkySporkness/FLUX.1-Canny-dev-GGUF/resolve/main/flux1-canny-dev-fp16-Q8_0-GGUF.gguf
        variant: default
        precision: q8_0
        type: gguf
        resource_requirements:
          min_vram_gb: 8
          recommended_vram_gb: 16
      - path: https://huggingface.co/SporkySporkness/FLUX.1-Canny-dev-GGUF/resolve/main/flux1-canny-dev-fp16-Q5_0-GGUF.gguf
        variant: default
        precision: q5_0
        type: gguf
        resource_requirements:
          min_vram_gb: 8
          recommended_vram_gb: 12
        recommended_vram_gb: 12
      - path: https://huggingface.co/SporkySporkness/FLUX.1-Canny-dev-GGUF/resolve/main/flux1-canny-dev-fp16-Q4_0-GGUF.gguf
        variant: default
        precision: q4_0
        type: gguf
        resource_requirements:
          min_vram_gb: 8
          recommended_vram_gb: 12
  
  defaults:
    run:
      num_inference_steps: 40
      guidance_scale: 5.0
      return_latents: false
      text_encoder_kwargs: 
        clean_text: false
        max_sequence_length: 77
        pad_with_zero: false
        add_special_tokens: true
      text_encoder_2_kwargs:
        add_special_tokens: true
        clean_text: false
        pad_with_zero: false
        max_sequence_length: 512
      attention_kwargs: {}
  ui:
    floating_panel:
      regions:
        top:
          inputs: [control_image]
          flow: column
        middle:
          inputs: [prompt]
          flow: column
        bottom:
          inputs: [resolution, aspect_ratio]
          flow: row

    panels:
      - name: generation
        label: Generation
        layout:
          flow: column
          rows:
            - [control_image]
            - [prompt]
            - [negative_prompt]
            - [resolution, aspect_ratio]
            - [num_inference_steps]
      
      - name: advanced
        label: Advanced Generation
        collapsible: true
        layout:
          flow: column
          rows:
            - [height, width]
            - [prompt_2]
            - [negative_prompt_2]
            - [seed]
            - [true_cfg_scale]
            - [guidance_scale]
    inputs:
      - id: control_image
        label: Control Image
        description: A canny edge image to guide the generation.
        type: image+preprocessor
        panel: generation
        preprocessor_ref: canny
        required: true
        floating_panel: true
          
      - id: prompt
        label: Prompt
        type: text
        panel: generation
        required: true
        floating_panel: true

      - id: negative_prompt
        label: Negative Prompt
        description: Describe what you want to avoid in the generation
        type: textarea
        panel: generation
        required: false
        default: "blurry, low quality, distorted, artifacts"
        floating_panel: false

      - id: resolution
        label: Resolution
        description: Select the resolution of the output image  
        panel: generation
        type: select
        default: 720
        icon: md/MdMonitor # React icons name 
        options:
          - name: HD (720p)
            value: 720
          - name: Full HD (1080p)
            value: 1080
          - name: SD (480p)
            value: 480
        floating_panel: true
        
      - id: aspect_ratio
        label: Aspect Ratio
        description: Select the aspect ratio of the output image.
        panel: generation
        type: select
        default: 16:9
        icon: md/MdAspectRatio
        options:
          - name: Wide (16:9)
            value: 16:9
          - name: Vertical (9:16)
            value: 9:16
          - name: Square (1:1)
            value: 1:1
          - name: Classic (3:4)
            value: 3:4
        floating_panel: true
      
      - id: num_inference_steps
        label: Inference Steps
        description: Number of denoising steps (higher = better quality but slower).
        type: number
        value_type: integer
        panel: generation
        default: 30
        min: 1
        max: 100
        step: 5
        floating_panel: false
      
      - id: height
        label: Height
        description: Enter the height of the output image.
        type: number
        value_type: integer
        panel: advanced
        default: 1024
        min: 256
        max: 8192
        step: 1
        floating_panel: false

      - id: width
        label: Width
        description: Enter the width of the output image.
        type: number
        value_type: integer
        panel: advanced
        default: 1024
        min: 256
        max: 8192
        step: 1
        floating_panel: false
      
      - id: prompt_2
        label: Prompt 2
        description: Enter a second prompt for the generation
        type: text
        panel: generation
        required: false
        floating_panel: false

      - id: negative_prompt_2
        label: Negative Prompt 2
        description: Enter a second negative prompt for the generation
        type: textarea
        panel: advanced
        required: false
        floating_panel: false

      - id: seed
        label: Seed
        description: Enter a random seed for controllably random generation.
        type: random
        default: -1
        min: 0
        max: 4294967295
        value_type: integer
        panel: advanced
        required: false
        floating_panel: false
      
      - id: true_cfg_scale
        label: True CFG Scale
        description: Enter a true CFG scale for the generation.
        type: number
        value_type: float
        panel: advanced
        required: false
        floating_panel: false
        default: 1.0
        min: 1.0
        max: 15.0
        step: 0.5

      - id: guidance_scale
        label: Guidance Scale
        description: Enter a guidance scale for the generation.
        type: number
        value_type: float
        panel: advanced
        required: false
        floating_panel: false
        default: 5.0
        min: 1.0
        max: 15.0
        step: 0.5