api_version: apex/v1
kind: Model
metadata:
  name: Flux Dev Kontext
  version: 1.0.0
  description: Flux is a 12B parameter model for text-to-image generation.
  tags:
  - flux
  - dev
  - kontext
spec:
  engine: flux
  model_type: kontext
  engine_type: torch
  denoise_type: base
  components:
  - type: scheduler
    base: diffusers.FlowMatchEulerDiscreteScheduler
    config_path: black-forest-labs/FLUX.1-Kontext-dev/scheduler/scheduler_config.json
  - type: vae
    base: auto
    model_path: black-forest-labs/FLUX.1-dev/vae
  - type: text_encoder
    name: text_encoder
    base: CLIPTextModel
    model_path: black-forest-labs/FLUX.1-dev/text_encoder
    tokenizer_class: CLIPTokenizer
    tokenizer_name: black-forest-labs/FLUX.1-dev
    tokenizer_kwargs:
      subfolder: tokenizer
  - type: text_encoder
    name: text_encoder_2
    base: T5EncoderModel
    model_path: black-forest-labs/FLUX.1-dev/text_encoder_2
    tokenizer_class: T5Tokenizer
    tokenizer_name: black-forest-labs/FLUX.1-dev
    tokenizer_kwargs:
      subfolder: tokenizer_2
  - type: transformer
    base: flux.base
    model_path: black-forest-labs/FLUX.1-Kontext-dev/transformer
  defaults:
    run:
      num_inference_steps: 40
      guidance_scale: 5.0
      return_latents: false
      text_encoder_kwargs: 
        clean_text: false
        max_sequence_length: 77
        pad_with_zero: false
        add_special_tokens: true
      text_encoder_2_kwargs:
        add_special_tokens: true
        clean_text: false
        pad_with_zero: false
        max_sequence_length: 512
      attention_kwargs: {}
